server:
  port: 8080
  # DataSource Config
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
spring:
  application:
    name: user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 160333whb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 0
#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
